# Calibrated Cup Positions
# Generated by calibration script

CUP_POSITIONS = [
    [89, 91, 90, 90, 89, 31],  # Cup 1
    [89, 91, 90, 90, 89, 31],  # Cup 2
    [90, 91, 90, 90, 89, 31],  # Cup 3
]

# Stack position (center)
STACK_POSITION = [90, 90, 90, 90, 90, 30]
