# Table Height Position
# Generated by elbow adjuster

TABLE_HEIGHT_POSITION = [90, 15, 70, 90, 90, 30]

# Servo descriptions:
# Servo 1 (Base): Rotation
# Servo 2 (Shoulder): Up/down movement
# Servo 3 (Elbow): Bend
# Servo 4 (Wrist): Rotation
# Servo 5 (Wrist): Tilt
# Servo 6 (Gripper): Open/close 